Repository googleapis/java-talent, pull requests merged in 2020-10, with the labels that each got.

#266 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#273 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes

#285 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#290 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#284 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: jobs, automerge, cla: yes

#295 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#296 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#298 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#300 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#301 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#304 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#302 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: jobs, automerge, cla: yes, context: full

#307 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#308 feat: promote to 1.0.0
  .repo-metadata.json
Labels: automerge, cla: yes

#310 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#314 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#315 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#317 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
