Repository googleapis/java-talent, pull requests merged in 2020-06, with the labels that each got.

#171 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#174 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#177 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#176 docs: Remove a broken link from the documentation.
  proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/LocationFilter.java
  proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/LocationFilterOrBuilder.java
  proto-google-cloud-talent-v4beta1/src/main/proto/google/cloud/talent/v4beta1/filters.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#179 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#185 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#189 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#195 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-talent/pom.xml
  grpc-google-cloud-talent-v4beta1/pom.xml
  pom.xml
  proto-google-cloud-talent-v4beta1/pom.xml
Labels: cla: yes

#194 fix: migrate retry settings to grpc_service_config
  README.md
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/ApplicationServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/ApplicationServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/CompanyServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/CompanyServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/JobServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/JobServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/ProfileServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/ProfileServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/TenantServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/TenantServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/package-info.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/ApplicationServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/ApplicationServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/CompanyServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/CompanyServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/CompletionStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/EventServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcApplicationServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcCompanyServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcJobServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcProfileServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcTenantServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/JobServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/JobServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/ProfileServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/ProfileServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/TenantServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/TenantServiceStubSettings.java
  google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/ApplicationServiceClientTest.java
  google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/CompanyServiceClientTest.java
  google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/JobServiceClientTest.java
  google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/ProfileServiceClientTest.java
  google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/TenantServiceClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#203 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
