Repository googleapis/java-talent, pull requests merged in 2021-08, with the labels that each got.

#561 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: jobs, automerge, context: full

#571 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: jobs, automerge

#567 feat!: release gapic-generator-java v2.0.0
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/CompanyServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/CompanyServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/CompletionSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/EventServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/JobServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/JobServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/TenantServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/TenantServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/CompanyServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/CompletionStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/EventServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/GrpcCompanyServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/GrpcCompletionStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/GrpcEventServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/GrpcJobServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/GrpcTenantServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/JobServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/TenantServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/ApplicationServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/ApplicationServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/CompanyServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/CompanyServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/CompletionSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/EventServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/JobServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/JobServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/ProfileServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/ProfileServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/TenantServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/TenantServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/ApplicationServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/CompanyServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/CompletionStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/EventServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcApplicationServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcCompanyServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcCompletionStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcEventServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcJobServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcProfileServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcTenantServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/JobServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/ProfileServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/TenantServiceStubSettings.java
  synth.metadata
Labels: cla: yes, api: jobs, automerge, context: full

#576 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: jobs, automerge

#578 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/nightly/integration.cfg
  synth.metadata
Labels: kokoro:force-run, cla: yes, api: jobs, automerge, context: full

#580 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: jobs, automerge

#583 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: jobs, automerge

#588 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: jobs, automerge

#589 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: jobs, automerge

#600 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: jobs, automerge

#601 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: jobs, automerge, context: full
