Repository googleapis/java-talent, pull requests merged in 2021-05, with the labels that each got.

#498 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: jobs, automerge, cla: yes, context: none

#499 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: jobs, automerge, cla: yes

#500 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: jobs, automerge, cla: yes, context: full

#504 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: jobs, automerge, cla: yes

#508 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: jobs, automerge, cla: yes, context: full

#509 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: jobs, automerge, cla: yes

#511 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: jobs, automerge, cla: yes

#512 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: jobs, automerge, cla: yes, context: full

#519 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: jobs, automerge, cla: yes, kokoro:force-run, kokoro:run

#520 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: jobs, automerge, cla: yes
