Repository googleapis/java-talent, pull requests merged in 2021-01, with the labels that each got.

#382 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: jobs, automerge, cla: yes

#383 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: jobs, automerge, cla: yes

#378 chore: update gapic-generator-java to 0.0.16
  google-cloud-talent/src/test/java/com/google/cloud/talent/v4/CompanyServiceClientTest.java
  google-cloud-talent/src/test/java/com/google/cloud/talent/v4/JobServiceClientTest.java
  google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/CompanyServiceClientTest.java
  google-cloud-talent/src/test/java/com/google/cloud/talent/v4beta1/JobServiceClientTest.java
  synth.metadata
Labels: api: jobs, automerge, cla: yes, context: full

#384 chore: update gapic-generator-java to 0.0.18
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/CompanyServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/CompletionClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/EventServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/JobServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/TenantServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/CompanyServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/CompanyServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/CompletionStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/CompletionStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/EventServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/EventServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/GrpcCompanyServiceCallableFactory.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/GrpcCompletionCallableFactory.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/GrpcEventServiceCallableFactory.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/GrpcJobServiceCallableFactory.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/GrpcTenantServiceCallableFactory.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/JobServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/JobServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/TenantServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4/stub/TenantServiceStubSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/ApplicationServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/ApplicationServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/CompanyServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/CompanyServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/CompletionClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/CompletionSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/EventServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/EventServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/JobServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/JobServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/ProfileServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/ProfileServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/TenantServiceClient.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/TenantServiceSettings.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/ApplicationServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/CompanyServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/CompletionStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/EventServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcApplicationServiceCallableFactory.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcApplicationServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcCompanyServiceCallableFactory.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcCompanyServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcCompletionCallableFactory.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcCompletionStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcEventServiceCallableFactory.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcEventServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcJobServiceCallableFactory.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcJobServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcProfileServiceCallableFactory.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcProfileServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcTenantServiceCallableFactory.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/GrpcTenantServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/JobServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/ProfileServiceStub.java
  google-cloud-talent/src/main/java/com/google/cloud/talent/v4beta1/stub/TenantServiceStub.java
  synth.metadata
Labels: api: jobs, cla: yes, context: full

#389 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: jobs, automerge, cla: yes

#391 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: jobs, automerge, cla: yes

#396 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: jobs, automerge, cla: yes, context: full

#397 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: jobs, automerge, cla: yes
