Repository googleapis/java-talent, pull requests merged in 2021-09, with the labels that each got.

#605 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: kokoro:force-run, cla: yes, api: jobs, automerge, context: full

#606 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  README.md
  google-cloud-talent-bom/pom.xml
  google-cloud-talent/pom.xml
  owlbot.py
  pom.xml
  proto-google-cloud-talent-v4beta1/src/main/java/com/google/cloud/talent/v4beta1/BatchProto.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchAutocompleteJobTitle.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchBatchCreateJobs.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchBatchDeleteJob.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchBatchUpdateJobs.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchCommuteSearch.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchCreateClientEvent.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchCreateCompany.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchCreateJob.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchCreateJobCustomAttributes.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchCreateTenant.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchCustomRankingSearch.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchDeleteCompany.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchDeleteJob.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchDeleteTenant.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchGetCompany.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchGetJob.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchGetTenant.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchHistogramSearch.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchListCompanies.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchListJobs.java
  samples/generated/src/main/java/com/google/cloud/examples/talent/v4beta1/JobSearchListTenants.java
  samples/snippets/src/main/java/com/example/jobs/JobSearchCreateJob.java
  samples/snippets/src/main/java/com/example/jobs/JobSearchCreateJobCustomAttributes.java
  samples/snippets/src/test/java/CommuteSearchJobsTest.java
  samples/snippets/src/test/java/CustomRankingSearchJobsTest.java
  samples/snippets/src/test/java/JobSearchCreateJobWithCustomAttrTest.java
  samples/snippets/src/test/java/JobSearchGetJobTest.java
  samples/snippets/src/test/java/JobSearchListJobsTest.java
  synth.py
Labels: cla: yes, api: jobs, automerge

#610 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: kokoro:force-run, cla: yes, api: jobs, automerge

#619 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: jobs, automerge

#629 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: jobs, automerge

#634 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: jobs, automerge
